-- MySQL Script generated by MySQL Workbench
-- Thu Nov  5 23:06:32 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`RENTER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`RENTER` (
  `ID` INT(19) NOT NULL AUTO_INCREMENT,
  `RENTER_NAME` VARCHAR(145) NULL,
  `RENTER_EMAIL` VARCHAR(145) NULL,
  `RENTER_PASSWORD` VARCHAR(145) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PRODUCT_SUBTYPE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PRODUCT_SUBTYPE` (
  `ID` INT(19) NOT NULL AUTO_INCREMENT,
  `PRODUCT_SUBTYPE_NAME` VARCHAR(145) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PRODUCT_TYPE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PRODUCT_TYPE` (
  `ID` INT(19) NOT NULL AUTO_INCREMENT,
  `PRODUCT_TYPE_NAME` VARCHAR(145) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PRODUCT_INVENTARY`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PRODUCT_INVENTARY` (
  `ID` INT(19) NOT NULL AUTO_INCREMENT,
  `STATE_INVENTARY` TINYINT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PRODUCT_PRICE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PRODUCT_PRICE` (
  `ID` INT(19) NOT NULL AUTO_INCREMENT,
  `PRICE_PER_DAY` DOUBLE NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PRODUCT_FEE_DELAY`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PRODUCT_FEE_DELAY` (
  `ID` INT(19) NOT NULL AUTO_INCREMENT,
  `PRODUCT_FEE_DELAY_PER_DAY` DOUBLE NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PRODUCT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PRODUCT` (
  `ID` INT(19) NOT NULL AUTO_INCREMENT,
  `PRODUCT_NAME` VARCHAR(145) NULL,
  `RENTER_ID` INT(19) NOT NULL,
  `PRODUCT_SUBTYPE_ID` INT(19) NOT NULL,
  `PRODUCT_TYPE_ID` INT(19) NOT NULL,
  `PRODUCT_INVENTARY_ID` INT(19) NOT NULL,
  `PRODUCT_PRICE_ID` INT(19) NOT NULL,
  `PRODUCT_FEE_DELAY_ID` INT(19) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_PRODUCT_RENTER_idx` (`RENTER_ID` ASC) VISIBLE,
  INDEX `fk_PRODUCT_PRODUCT_SUBTYPE1_idx` (`PRODUCT_SUBTYPE_ID` ASC) VISIBLE,
  INDEX `fk_PRODUCT_PRODUCT_TYPE1_idx` (`PRODUCT_TYPE_ID` ASC) VISIBLE,
  INDEX `fk_PRODUCT_PRODUCT_INVENTARY1_idx` (`PRODUCT_INVENTARY_ID` ASC) VISIBLE,
  INDEX `fk_PRODUCT_PRODUCT_PRICE1_idx` (`PRODUCT_PRICE_ID` ASC) VISIBLE,
  INDEX `fk_PRODUCT_PRODUCT_FEE_DELAY1_idx` (`PRODUCT_FEE_DELAY_ID` ASC) VISIBLE,
  CONSTRAINT `fk_PRODUCT_RENTER`
    FOREIGN KEY (`RENTER_ID`)
    REFERENCES `mydb`.`RENTER` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PRODUCT_PRODUCT_SUBTYPE1`
    FOREIGN KEY (`PRODUCT_SUBTYPE_ID`)
    REFERENCES `mydb`.`PRODUCT_SUBTYPE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PRODUCT_PRODUCT_TYPE1`
    FOREIGN KEY (`PRODUCT_TYPE_ID`)
    REFERENCES `mydb`.`PRODUCT_TYPE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PRODUCT_PRODUCT_INVENTARY1`
    FOREIGN KEY (`PRODUCT_INVENTARY_ID`)
    REFERENCES `mydb`.`PRODUCT_INVENTARY` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PRODUCT_PRODUCT_PRICE1`
    FOREIGN KEY (`PRODUCT_PRICE_ID`)
    REFERENCES `mydb`.`PRODUCT_PRICE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PRODUCT_PRODUCT_FEE_DELAY1`
    FOREIGN KEY (`PRODUCT_FEE_DELAY_ID`)
    REFERENCES `mydb`.`PRODUCT_FEE_DELAY` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`RENT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`RENT` (
  `ID` INT(19) NOT NULL AUTO_INCREMENT,
  `RENT_COST` DOUBLE NULL,
  `RENT_COST_DELAY` DOUBLE NULL,
  `RENT_DAYS` INT NULL,
  `RENT_REAL_DAYS` INT NULL,
  `RENT_REAL_COST` INT NULL,
  `RENTER_ID` INT(19) NOT NULL,
  `PRODUCT_ID` INT(19) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_RENT_RENTER1_idx` (`RENTER_ID` ASC) VISIBLE,
  INDEX `fk_RENT_PRODUCT1_idx` (`PRODUCT_ID` ASC) VISIBLE,
  CONSTRAINT `fk_RENT_RENTER1`
    FOREIGN KEY (`RENTER_ID`)
    REFERENCES `mydb`.`RENTER` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RENT_PRODUCT1`
    FOREIGN KEY (`PRODUCT_ID`)
    REFERENCES `mydb`.`PRODUCT` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`RENT_NOTIFICATION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`RENT_NOTIFICATION` (
  `ID` INT(19) NOT NULL AUTO_INCREMENT,
  `HTML` VARCHAR(1000) NULL,
  `TYPE` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`IMGS_SUBTYPE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`IMGS_SUBTYPE` (
  `ID` INT(19) NOT NULL AUTO_INCREMENT,
  `URL` VARCHAR(545) NULL,
  `PRODUCT_SUBTYPE_ID` INT(19) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_IMGS_SUBTYPE_PRODUCT_SUBTYPE1_idx` (`PRODUCT_SUBTYPE_ID` ASC) VISIBLE,
  CONSTRAINT `fk_IMGS_SUBTYPE_PRODUCT_SUBTYPE1`
    FOREIGN KEY (`PRODUCT_SUBTYPE_ID`)
    REFERENCES `mydb`.`PRODUCT_SUBTYPE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ROLE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ROLE` (
  `ID` INT(19) NOT NULL AUTO_INCREMENT,
  `ROLE_TYPE` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`RENTER_ROLE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`RENTER_ROLE` (
  `RENTER_ID` INT(19) NOT NULL,
  `ROLE_ID` INT(19) NOT NULL,
  PRIMARY KEY (`RENTER_ID`, `ROLE_ID`),
  INDEX `fk_RENTER_has_ROLE_ROLE1_idx` (`ROLE_ID` ASC) VISIBLE,
  INDEX `fk_RENTER_has_ROLE_RENTER1_idx` (`RENTER_ID` ASC) VISIBLE,
  CONSTRAINT `fk_RENTER_has_ROLE_RENTER1`
    FOREIGN KEY (`RENTER_ID`)
    REFERENCES `mydb`.`RENTER` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RENTER_has_ROLE_ROLE1`
    FOREIGN KEY (`ROLE_ID`)
    REFERENCES `mydb`.`ROLE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
